-- # populater table user
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Anna', 'Annalisi', '1991-01-01', 'aaa', 'aaa@aaa.aaa', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Alex', 'Alexandria', '1992-02-02', 'bbb', 'bbb@bbb.bbb', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Francesco', 'Dries', '1993-03-03', 'ccc', 'ccc@ccc.ccc', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Dario', 'Francescani', '1994-04-04', 'ddd', 'ddd@ddd.ddd', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Kevin', 'Malone', '1995-05-05', 'eee', 'eee@eee.eee', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Peter', 'Pan', '1996-06-06', 'fff', 'fff@fff.fff', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Soy', 'Milk', '1997-07-07', 'ggg', 'ggg@ggg.ggg', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Wiktoria', 'Violent', '1998-08-08', 'hhh', 'hhh@hhh.hhh', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Leo', 'Lei', '1999-09-09', 'iii', 'iii@iii.iii', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Marko', 'Marki', '2000-10-10', 'jjj', 'jjj@jjj.jjj', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Drako', 'Malfoy', '2001-11-11', 'kkk', 'kkk@kkk.kkk', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('George', 'Jorgenson', '2002-12-12', 'lll', 'lll@lll.lll', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Derrik', 'Fervik', '2003-01-01', 'mmm', 'mmm@mmm.mmm', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Maria', 'Santa', '1994-02-02', 'nnn', 'nnn@nnn.nnn', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Johannes', 'Jovi', '1995-03-03', 'ooo', 'ooo@ooo.ooo', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Dario', 'Fring', '1996-04-04', 'ppp', 'ppp@ppp.ppp', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Michael', 'Micheloni', '1994-05-05', 'qqq', 'qqq@qqq.qqq', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Trevis', 'Scott', '1995-06-06', 'rrr', 'rrr@rrr.rrr', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Trevor', 'Tremble', '1997-07-07', 'sss', 'sss@sss.sss', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Katharina', 'Holland', '2002-08-08', 'ttt', 'ttt@ttt.ttt', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Sophia', 'Sullivan', '1998-09-09', 'uuu', 'uuu@uuu.uuu', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Oliver', 'Oliverson', '1999-10-10', 'vvv', 'vvv@vvv.vvv', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Emma', 'Emmerson', '2000-11-11', 'www', 'www@www.www', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Noah', 'Nolan', '2001-12-12', 'xxx', 'xxx@xxx.xxx', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Liam', 'Liamson', '2002-01-01', 'yyy', 'yyy@yyy.yyy', '2023-06-09');
INSERT INTO present.user (firstName, lastName, dateOfBirth, password, email, registrationTime) VALUES ('Ava', 'Anderson', '1996-02-02', 'zzz', 'zzz@zzz.zzz', '2023-06-09');
-- # populate table connections
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (1, 5, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (1, 7, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (1, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (1, 10, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (1, 19, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (1, 15, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (3, 2, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (3, 5, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (3, 8, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (3, 12, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (3, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (3, 20, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (3, 9, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (2, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (2, 1, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (2, 14, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (2, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (4, 6, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (4, 9, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (4, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (4, 20, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (4, 11, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (4, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 12, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 1, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 13, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 15, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 20, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (5, 2, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (6, 14, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (6, 7, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (6, 8, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (6, 16, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (6, 9, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (6, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (7, 2, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (7, 1, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (7, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (11, 5, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (11, 7, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (11, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (11, 10, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (11, 19, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (11, 15, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (13, 2, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (13, 5, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (13, 8, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (13, 12, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (13, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (13, 20, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (13, 9, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 1, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 14, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 6, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 9, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 17, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (19, 20, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (14, 11, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (14, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 12, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 3, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 1, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 13, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 16, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 20, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (15, 2, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (16, 14, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (16, 7, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (16, 8, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (9, 16, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (16, 9, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (16, 18, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (17, 2, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (17, 1, '2023-06-09');
INSERT INTO present.connections (userId, connectedTo, connectedOn) VALUES (17, 3, '2023-06-09');

-- populate table event
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (1, 'My Birthday', '2023-10-10 12:00:00', 'Restaurant XY in Exampletown', 'false', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (2, 'House Warming', '2023-07-10 18:30:00', 'My new place in Example Street', 'false', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (3, 'Baby Shower! Little Leslie will soon be with us', '2023-07-25 10:45:00', 'My parent´s farm outside the city. Follow directions for "Beetroot Paradise"', 'false', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (4, 'Celebrate our Team´s promotion to the higher league', '2023-06-20 12:00:00', 'Botanical Garden in Pleasantville', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (5, 'Charity Fundraiser Gala', '2023-09-15 19:00:00', 'Grand Hotel Ballroom', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (6, 'Annual Boys get Together', '2023-07-15 19:00:00', 'My Flat', 'false', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (8, 'Outdoor Music Festival', '2023-07-30 14:00:00', 'Greenfield Park', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (7, 'Me and Jolie are finally getting married', '2023-08-05 17:30:00', 'Luxury Resort', 'false', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (9, 'Art Workshop', '2023-07-30 14:00:00', 'Community Art Studio', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (10, 'Family Reunion BBQ', '2023-09-02 12:00:00', 'Smith Family Farm', 'false', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (11, 'Tech Startup Demo Day', '2023-09-02 09:00:00', 'Innovation Hub', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (12, 'Sports Tournament Finals', '2023-08-27 15:00:00', 'Main Stadium', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (13, 'Condo monthly meeting', '2023-08-27 20:00:00', 'Conference Room - ground floor', 'false', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (14, 'Fix the public gardens', '2023-09-10 14:00:00', 'Park down the street', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (15, 'Community Volunteer Day', '2023-07-17 09:00:00', 'Local Community Center', 'true', '2023-06-13');
INSERT INTO present.event (organizedBy, name, date, place, public, creationTime) VALUES (1, 'Lord of the Rings Marathon Night', '2023-08-12 18:00:00', 'Filippo`s House', 'false', '2023-06-13');

-- populate table guests
INSERT INTO present.guests (guestId, eventId) VALUES (2, 1);
INSERT INTO present.guests (guestId, eventId) VALUES (3, 1);
INSERT INTO present.guests (guestId, eventId) VALUES (3, 2);
INSERT INTO present.guests (guestId, eventId) VALUES (5, 1);
INSERT INTO present.guests (guestId, eventId) VALUES (7, 1);
INSERT INTO present.guests (guestId, eventId) VALUES (15, 1);
INSERT INTO present.guests (guestId, eventId) VALUES (5, 2);
INSERT INTO present.guests (guestId, eventId) VALUES (7, 2);
INSERT INTO present.guests (guestId, eventId) VALUES (12, 2);
INSERT INTO present.guests (guestId, eventId) VALUES (15, 2);
INSERT INTO present.guests (guestId, eventId) VALUES (18, 2);
INSERT INTO present.guests (guestId, eventId) VALUES (1, 3);
INSERT INTO present.guests (guestId, eventId) VALUES (7, 3);
INSERT INTO present.guests (guestId, eventId) VALUES (8, 3);
INSERT INTO present.guests (guestId, eventId) VALUES (3, 3);
INSERT INTO present.guests (guestId, eventId) VALUES (2, 6);
INSERT INTO present.guests (guestId, eventId) VALUES (7, 6);
INSERT INTO present.guests (guestId, eventId) VALUES (11, 6);
INSERT INTO present.guests (guestId, eventId) VALUES (19, 6);
INSERT INTO present.guests (guestId, eventId) VALUES (20, 6);
INSERT INTO present.guests (guestId, eventId) VALUES (8, 6);
INSERT INTO present.guests (guestId, eventId) VALUES (4, 8);
INSERT INTO present.guests (guestId, eventId) VALUES (7, 8);
INSERT INTO present.guests (guestId, eventId) VALUES (13, 8);
INSERT INTO present.guests (guestId, eventId) VALUES (14, 8);
INSERT INTO present.guests (guestId, eventId) VALUES (15, 8);
INSERT INTO present.guests (guestId, eventId) VALUES (20, 8);
INSERT INTO present.guests (guestId, eventId) VALUES (1, 10);
INSERT INTO present.guests (guestId, eventId) VALUES (7, 10);
INSERT INTO present.guests (guestId, eventId) VALUES (12, 10);
INSERT INTO present.guests (guestId, eventId) VALUES (17, 10);
INSERT INTO present.guests (guestId, eventId) VALUES (11, 13);
INSERT INTO present.guests (guestId, eventId) VALUES (16, 13);
INSERT INTO present.guests (guestId, eventId) VALUES (18, 13);
INSERT INTO present.guests (guestId, eventId) VALUES (1, 16);
INSERT INTO present.guests (guestId, eventId) VALUES (7, 16);
INSERT INTO present.guests (guestId, eventId) VALUES (8, 16);
INSERT INTO present.guests (guestId, eventId) VALUES (3, 16);
INSERT INTO present.guests (guestId, eventId) VALUES (11, 16);
